lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
collections:
  prototypes:
    output: true
  components:
    output: false
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      background: "garage.jpg"
      alpha: false
      failed: false
url: https://innovationgarage.github.io/prototype-web

